import type { DesignStyle } from '@prisma/client';

export type StyleTier = 'FREE' | 'PRO';

export type StyleCategory = 'ECOMMERCE' | 'SOCIAL_CREATOR' | 'LINKEDIN_BIZ' | 'NEWS_MEDIA' | 'TECH_SCIENCE';

export type StyleDef = {
  id: DesignStyle;
  label: string;
  subLabel?: string;
  description: string;
  tier: StyleTier;
  available: boolean;
  accentColor: string;
  bgColor: string;
  textColor: string;
  isLight?: boolean;
  badge?: string;
  instagramRef?: string;
  requiresBrandKit?: boolean;
  category?: StyleCategory;
  platformBadge?: string;
};

export const STYLES: StyleDef[] = [
  // ─── 3 TEMPLATE GRATIS (TRIAL & GUEST) ───
  {
    id: 'BREAKING_NEWS',
    label: 'Promo Kilat & Flash Sale',
    subLabel: 'ala Promo Diskon & Sale Terbatas',
    description: 'Banner merah tebal, foto hero produk/menu penuh, badge PROMO SPESIAL.',
    tier: 'FREE',
    available: true,
    accentColor: '#EF4444',
    bgColor: '#0B0F19',
    textColor: '#FFFFFF',
    isLight: false,
    badge: 'GRATIS',
    instagramRef: '@promo.diskon',
  },
  {
    id: 'EDITORIAL',
    label: 'Artisanal & Kuliner Asli',
    subLabel: 'ala Rumah Makan Padang & Kuliner Nusantara',
    description: 'Kertas krem hangat, tipografi serif berkelas, cocok untuk kisah brand, menu signature & resep.',
    tier: 'FREE',
    available: true,
    accentColor: '#B91C1C',
    bgColor: '#FDFBF7',
    textColor: '#1C1917',
    isLight: true,
    badge: 'GRATIS',
    instagramRef: '@padang.otentik',
  },
  {
    id: 'MODERN',
    label: 'Modern Cafe & Brand',
    subLabel: 'ala Fore Coffee & Cafe Kekinian',
    description: 'Foto band estetis, aksen biru sky, badge menu baru, layout bersih kontemporer.',
    tier: 'FREE',
    available: true,
    accentColor: '#0EA5E9',
    bgColor: '#0B132B',
    textColor: '#FFFFFF',
    isLight: false,
    badge: 'GRATIS',
    instagramRef: '@fore.coffee',
  },

  // ─── 17 TEMPLATE PRO EKSKLUSIF (LOCKED 🔒) ───
  {
    id: 'FINANCE',
    label: 'Tips Bisnis & Cuan',
    subLabel: 'ala @ngomonginuang & Scale-Up UMKM',
    description: 'Emerald green & navy cuan, kartu data rapi, metrik omset & strategi profit bisnis.',
    tier: 'PRO',
    available: true,
    accentColor: '#10B981',
    bgColor: '#022C22',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '🔒 PRO',
    instagramRef: '@tipsbisnis.id',
  },
  {
    id: 'TECH',
    label: 'SaaS & Otomasi UMKM',
    subLabel: 'ala Software POS, CRM & AI Tools',
    description: 'Tema gelap modern, aksen neon cyan/gold, kartu fitur & automasi bisnis digital.',
    tier: 'PRO',
    available: true,
    accentColor: '#06B6D4',
    bgColor: '#050B14',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '🔒 PRO',
    instagramRef: '@automasibisnis',
  },
  {
    id: 'LIFESTYLE',
    label: 'Skincare & Beauty Glow',
    subLabel: 'ala Brand Skincare & Beauty Care',
    description: 'Kartu peach pastel lembut, font elegan bersahabat, ikon beauty & perawatan rapi.',
    tier: 'PRO',
    available: true,
    accentColor: '#DB2777',
    bgColor: '#FFF7ED',
    textColor: '#1E293B',
    isLight: true,
    badge: '🔒 PRO',
    instagramRef: '@skincare.glow',
  },
  {
    id: 'BOLD',
    label: 'Mega Sale & Launching',
    subLabel: 'ala Grand Opening & Diskon Besar',
    description: 'Tipografi ultra-bold kontras tinggi, aksen kuning menyala, magnet perhatian di feed.',
    tier: 'PRO',
    available: true,
    accentColor: '#FACC15',
    bgColor: '#000000',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '🔒 PRO',
    instagramRef: '@megasale.id',
  },
  {
    id: 'CORPORATE',
    label: 'Profil Bisnis & B2B',
    subLabel: 'ala Solusi Perusahaan & B2B',
    description: 'Desain korporat bersih, kartu value proposition bertingkat, layout profesional.',
    tier: 'PRO',
    available: true,
    accentColor: '#3B82F6',
    bgColor: '#0F172A',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '🔒 PRO',
    instagramRef: '@b2bsolusi',
  },
  {
    id: 'CUSTOM_BRAND',
    label: 'Fakta Brand & Trivia',
    subLabel: 'ala Edukasi Pelanggan & Mitos Fakta',
    description: 'Warna pop vibrant, kartu Fakta vs Mitos produk, memancing interaksi & rasa penasaran pembeli.',
    tier: 'PRO',
    available: true,
    accentColor: '#A855F7',
    bgColor: '#1E1B4B',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '🔒 PRO',
    instagramRef: '@edukasi.brand',
  },
  {
    id: 'MINIMAL',
    label: 'Katalog Produk Studio',
    subLabel: 'ala Studio Foto & Katalog Minimalis',
    description: 'Kanvas putih bersih, frame presisi, tipografi elegan, menonjolkan detail produk.',
    tier: 'PRO',
    available: true,
    accentColor: '#4F46E5',
    bgColor: '#FFFFFF',
    textColor: '#09090B',
    isLight: true,
    badge: '🔒 PRO',
    instagramRef: '@katalog.studio',
  },

  // ─── 10 TEMPLATE MASTER BARU ───
  {
    id: 'STREETWEAR',
    label: 'Streetwear Urban Hook',
    subLabel: 'ala Youth Media & Street Fashion',
    description: 'Foto potret streetwear ukuran penuh dengan kartu putih melayang di sepertiga bawah.',
    tier: 'PRO',
    available: true,
    accentColor: '#000000',
    bgColor: '#FAFAFA',
    textColor: '#000000',
    isLight: true,
    badge: '✨ BARU',
    instagramRef: '@hypebeastid',
  },
  {
    id: 'BLOOMBERG',
    label: 'Bloomberg Market Terminal',
    subLabel: 'ala Financial Executive',
    description: 'Ticker bar harga pasar berjalan, kontras hijau zamrud, kartu analisis finansial tajam.',
    tier: 'PRO',
    available: true,
    accentColor: '#22C55E',
    bgColor: '#021D17',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '✨ BARU',
    instagramRef: '@bloombergasia',
  },
  {
    id: 'TERMINAL',
    label: 'MacOS Code Terminal',
    subLabel: 'ala Software & AI Dispatch',
    description: 'Jendela editor kode dengan 3 dot macOS (🔴🟡🟢), font monospace Fira Code & prompt cyan.',
    tier: 'PRO',
    available: true,
    accentColor: '#06B6D4',
    bgColor: '#050811',
    textColor: '#38BDF8',
    isLight: false,
    badge: '✨ BARU',
    instagramRef: '@codepolitan',
  },
  {
    id: 'ATHLETIC',
    label: 'Nike Athletic Speed Poster',
    subLabel: 'ala RedBull & Nike Sport',
    description: 'Garis balap diagonal 15 derajat, tipografi condensed ekstra tebal, kontras kuning balap.',
    tier: 'PRO',
    available: true,
    accentColor: '#EAB308',
    bgColor: '#000000',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '✨ BARU',
    instagramRef: '@nikerunning',
  },
  {
    id: 'COSMIC',
    label: 'Observatory Cosmic Science',
    subLabel: 'ala Riset Sains & Astronomi',
    description: 'Pendaran nebula luar angkasa, kisi koordinat teleskop, kartu observasi emas solar.',
    tier: 'PRO',
    available: true,
    accentColor: '#F59E0B',
    bgColor: '#030712',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '✨ BARU',
    instagramRef: '@nasaindonesia',
  },
  {
    id: 'POLICY',
    label: 'Official Policy White Paper',
    subLabel: 'ala Diplomasi & Regulasi',
    description: 'Kertas dokumen resmi, double-rule crimson masthead, tipografi serif Playfair berwibawa.',
    tier: 'PRO',
    available: true,
    accentColor: '#991B1B',
    bgColor: '#F8FAFC',
    textColor: '#0F172A',
    isLight: true,
    badge: '✨ BARU',
    instagramRef: '@kebijakanpublik',
  },
  {
    id: 'SPOTLIGHT',
    label: 'Billboard & Netflix Spotlight',
    subLabel: 'ala Film & Pop Culture',
    description: 'Lencana neon TRENDING #1, kartu kaca frosted ungu-magenta, rating bintang ulasan.',
    tier: 'PRO',
    available: true,
    accentColor: '#D946EF',
    bgColor: '#1E1035',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '✨ BARU',
    instagramRef: '@netflixid',
  },
  {
    id: 'RED_COLLAGE',
    label: 'Red Highlight Urban Banner',
    subLabel: 'ala Streetwear & Underground Beats',
    description: 'Kolase urban street, inset foto lingkaran, pita merah solid bertumpuk di judul.',
    tier: 'PRO',
    available: true,
    accentColor: '#EF4444',
    bgColor: '#0A0A0C',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '✨ BARU',
    instagramRef: '@ussfeed',
  },
  {
    id: 'PODCAST',
    label: 'Podcast Interview Persona',
    subLabel: 'ala Sosok Bisnis & Founder Talk',
    description: 'Studio wawancara modern, balon kutipan hitam bertumpuk, lencana sosok inspiratif.',
    tier: 'PRO',
    available: true,
    accentColor: '#2563EB',
    bgColor: '#F4F4F5',
    textColor: '#18181B',
    isLight: true,
    badge: '✨ BARU',
    instagramRef: '@podcastfoundertalk',
  },
  {
    id: 'CULINARY',
    label: 'Viral Culinary Neon Indigo',
    subLabel: 'ala Food Vlogger & Kuliner Viral',
    description: 'Foto makanan viral menggiurkan, gradasi midnight indigo pekat bawah, lencana tag lokasi.',
    tier: 'PRO',
    available: true,
    accentColor: '#6366F1',
    bgColor: '#0F172A',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '✨ BARU',
    instagramRef: '@kulinerindonesia',
    category: 'SOCIAL_CREATOR',
    platformBadge: '🍲 Kuliner & Cafe',
  },

  // ─── 12 TEMPLATE E-COMMERCE, PROMO & KREATOR SOSMED BARU ───
  {
    id: 'SHOPEE_PROMO',
    label: 'Shopee Flash Sale & Mega Promo',
    subLabel: 'ala Promo Gajian & Diskon Kilat',
    description: 'Aksen oranye Shopee cerah, badge petir miring, kartu harga coret, stiker COD & Gratis Ongkir.',
    tier: 'PRO',
    available: true,
    accentColor: '#EE4D2D',
    bgColor: '#1A0B06',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '🔥 FLASH SALE',
    instagramRef: '@shopee_id',
    category: 'ECOMMERCE',
    platformBadge: '🛍️ Shopee & IG Shop',
  },
  {
    id: 'RACUN_SHOPEE',
    label: 'Racun Shopee & Honest Review',
    subLabel: 'ala Affiliate Review TikTok & IG',
    description: 'Desain aesthetic affiliate viral, rating bintang 5, badge Racun Shopee Cek, checklist kelebihan produk.',
    tier: 'PRO',
    available: true,
    accentColor: '#FF6B6B',
    bgColor: '#0D1117',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '✨ VIRAL AFFILIATE',
    instagramRef: '@racunshopee.aesthetic',
    category: 'ECOMMERCE',
    platformBadge: '📦 Affiliate & Review',
  },
  {
    id: 'PRODUCT_CATALOG',
    label: 'Luxury Boutique & Skincare',
    subLabel: 'ala Brand Skincare & Pinterest Zara',
    description: 'Frame foto kubah arch aesthetic, warna warm nude cream, tipografi serif elegan, lencana BPOM & Halal.',
    tier: 'PRO',
    available: true,
    accentColor: '#C5A880',
    bgColor: '#FAF7F2',
    textColor: '#26211C',
    isLight: true,
    badge: '🧴 LUXURY CATALOG',
    instagramRef: '@somethincofficial',
    category: 'ECOMMERCE',
    platformBadge: '✨ Skincare & Fashion',
  },
  {
    id: 'BRUTALIST_SALE',
    label: 'Y2K Neo-Brutalist Pop Shop',
    subLabel: 'ala Streetwear & Distro Gen-Z',
    description: 'Outline hitam 3px tebal, bayangan solid drop shadow, stiker barcode harga supermarket, warna lime green neon.',
    tier: 'PRO',
    available: true,
    accentColor: '#CCFF00',
    bgColor: '#121212',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '⚡ GEN-Z BRUTALIST',
    instagramRef: '@thanksinsomnia',
    category: 'ECOMMERCE',
    platformBadge: '🏷️ Distro & Streetwear',
  },
  {
    id: 'BEFORE_AFTER',
    label: 'Before vs After Transformasi',
    subLabel: 'ala Klinik, Skincare & Fitness',
    description: 'Split-screen 50/50 merah vs emerald green, perbandingan hasil nyata masalah vs solusi, metrik 7 hari.',
    tier: 'PRO',
    available: true,
    accentColor: '#10B981',
    bgColor: '#0B0F17',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '⚖️ PROVEN RESULT',
    instagramRef: '@erhaderma',
    category: 'ECOMMERCE',
    platformBadge: '✨ Solusi & Hasil',
  },
  {
    id: 'TESTIMONIAL_CHAT',
    label: 'Bukti Chat WhatsApp & DM',
    subLabel: 'ala Review Pelanggan Asli Olshop',
    description: 'Balon chat hijau WhatsApp asli dengan centang biru, profil pembeli, kutipan kepuasan barang original.',
    tier: 'PRO',
    available: true,
    accentColor: '#25D366',
    bgColor: '#0C1317',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '💬 REAL CHAT',
    instagramRef: '@testimoni.olshop',
    category: 'ECOMMERCE',
    platformBadge: '💬 Testimoni Asli',
  },
  {
    id: 'PRICE_TIER_TABLE',
    label: 'Daftar Harga & Paket Menu',
    subLabel: 'ala Price List Jasa, Salon & Resto',
    description: 'Tiga kartu tingkatan paket (Hemat, Best Seller, Sultan), pita paling laris, dan checklist fitur lengkap.',
    tier: 'PRO',
    available: true,
    accentColor: '#F59E0B',
    bgColor: '#0F172A',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '📋 PRICE LIST',
    instagramRef: '@pricelist.studio',
    category: 'ECOMMERCE',
    platformBadge: '🏷️ Menu & Jasa',
  },
  {
    id: 'UNBOXING_POLAROID',
    label: 'Polaroid Scrapbook & Washi Tape',
    subLabel: 'ala Aesthetic Lifestyle & Unboxing',
    description: 'Bingkai foto polaroid miring dengan aksen selotip washi tape transparan, font tulisan tangan, stiker scrapbook.',
    tier: 'PRO',
    available: true,
    accentColor: '#F472B6',
    bgColor: '#FDF8F5',
    textColor: '#292524',
    isLight: true,
    badge: '📸 POLAROID',
    instagramRef: '@aestheticjournal.id',
    category: 'ECOMMERCE',
    platformBadge: '🎀 Aesthetic Olshop',
  },
  {
    id: 'TWITTER_THREAD',
    label: 'Cuitan Viral Twitter / X Thread',
    subLabel: 'ala Verified Influencer & Edukasi',
    description: 'Kartu tweet resmi Twitter/X dark mode, avatar centang biru verified, metrik retweet & like, hook viral.',
    tier: 'PRO',
    available: true,
    accentColor: '#1D9BF0',
    bgColor: '#000000',
    textColor: '#E7E9EA',
    isLight: false,
    badge: '🐦 VIRAL TWEET',
    instagramRef: '@xthreads.id',
    category: 'SOCIAL_CREATOR',
    platformBadge: '🐦 Viral Thread',
  },
  {
    id: 'QUOTE_MINIMAL',
    label: 'Big Typography Minimalist Quote',
    subLabel: 'ala Founder Mindset & Buku Filosofis',
    description: 'Tanda kutip raksasa monokrom di latar belakang, tipografi bold berani, kontras hitam putih berwibawa.',
    tier: 'PRO',
    available: true,
    accentColor: '#FFFFFF',
    bgColor: '#09090B',
    textColor: '#FAFAFA',
    isLight: false,
    badge: '🖋️ DEEP QUOTE',
    instagramRef: '@filosofi_hidup',
    category: 'SOCIAL_CREATOR',
    platformBadge: '🖋️ Motivasi & Mindset',
  },
  {
    id: 'STEP_BY_STEP_GUIDE',
    label: 'Step-by-Step Roadmap & Tutorial',
    subLabel: 'ala Panduan Praktis & Resep',
    description: 'Angka langkah raksasa 01, 02, 03, progress bar horizontal di atas kanvas, sangat pas untuk tutorial praktis.',
    tier: 'PRO',
    available: true,
    accentColor: '#8B5CF6',
    bgColor: '#0F172A',
    textColor: '#F8FAFC',
    isLight: false,
    badge: '🔢 ROADMAP',
    instagramRef: '@caramasakpraktis',
    category: 'SOCIAL_CREATOR',
    platformBadge: '📚 Tutorial & Resep',
  },
  {
    id: 'EVENT_WEBINAR',
    label: 'Poster Tiket Event & Webinar',
    subLabel: 'ala Tiket Konser & Kuliah Tamu',
    description: 'Format lanyard tiket dengan barcode, tanggal & jam besar, foto pembicara dengan ring glow emas.',
    tier: 'PRO',
    available: true,
    accentColor: '#EC4899',
    bgColor: '#180B22',
    textColor: '#FFFFFF',
    isLight: false,
    badge: '🎟️ TIKET EVENT',
    instagramRef: '@eventkampus',
    category: 'LINKEDIN_BIZ',
    platformBadge: '🎟️ Event & Webinar',
  },
];

export const AVAILABLE_STYLES = STYLES.filter((s) => s.available);
export const FREE_STYLES = AVAILABLE_STYLES.filter((s) => s.tier === 'FREE');
export const PRO_STYLES = AVAILABLE_STYLES.filter((s) => s.tier === 'PRO');
export const DEFAULT_STYLE: DesignStyle = 'BREAKING_NEWS';

export function isProStyle(style: DesignStyle): boolean {
  const def = STYLES.find((s) => s.id === style);
  return def?.tier === 'PRO';
}
