import type { DesignStyle } from '@prisma/client';

export type StyleTier = 'FREE' | 'PRO';

export type StyleDef = {
  id: DesignStyle;
  label: string;
  subLabel?: string;
  description: string;
  tier: StyleTier;
  available: boolean;
  accentColor: string;
  bgColor: string;
  textColor: string;
  badge?: string;
  instagramRef?: string;
  requiresBrandKit?: boolean;
};

export const STYLES: StyleDef[] = [
  // ─── 3 TEMPLATE GRATIS (TRIAL & GUEST) ───
  {
    id: 'BREAKING_NEWS',
    label: 'Breaking News Standar',
    subLabel: 'ala Portal Berita Populer',
    description: 'Format berita standar, banner merah tegas, foto latar, badge BREAKING.',
    tier: 'FREE',
    available: true,
    accentColor: '#EF4444',
    bgColor: '#0B0F19',
    textColor: '#FFFFFF',
    badge: 'GRATIS',
    instagramRef: '@beritaterkini',
  },
  {
    id: 'EDITORIAL',
    label: 'Editorial Nasional',
    subLabel: 'ala Jurnalisme Nasional',
    description: 'Format jurnalisme berita umum dengan tipografi serif koran standar.',
    tier: 'FREE',
    available: true,
    accentColor: '#DC2626',
    bgColor: '#18181B',
    textColor: '#FFFFFF',
    badge: 'GRATIS',
    instagramRef: '@redaksinasional',
  },
  {
    id: 'MODERN',
    label: 'Modern Clean Media',
    subLabel: 'ala Media Berita Bersih',
    description: 'Layout geometris sederhana, aksen biru sky, tipografi sans-serif standar.',
    tier: 'FREE',
    available: true,
    accentColor: '#0EA5E9',
    bgColor: '#0F172A',
    textColor: '#FFFFFF',
    badge: 'GRATIS',
    instagramRef: '@portalmodern',
  },

  // ─── 17 TEMPLATE PRO EKSKLUSIF (LOCKED 🔒) ───
  {
    id: 'FINANCE',
    label: 'Finansial & Cuan',
    subLabel: 'ala @ngomonginuang & @mikirduit',
    description: 'Emerald green & deep navy, kartu data rapi, angka metrik tebal, sangat berwibawa.',
    tier: 'PRO',
    available: true,
    accentColor: '#10B981',
    bgColor: '#064E3B',
    textColor: '#FFFFFF',
    badge: '🔒 PRO',
    instagramRef: '@ngomonginuang',
  },
  {
    id: 'TECH',
    label: 'Saham & Trading Tech',
    subLabel: 'ala @supercuansaham.id',
    description: 'Tema gelap modern, aksen neon gold/cyan, kartu ticker & analisis poin padat.',
    tier: 'PRO',
    available: true,
    accentColor: '#F59E0B',
    bgColor: '#0F172A',
    textColor: '#FFFFFF',
    badge: '🔒 PRO',
    instagramRef: '@supercuansaham.id',
  },
  {
    id: 'LIFESTYLE',
    label: 'Tentang Kampus & Edukasi',
    subLabel: 'ala @tentangkampus_id',
    description: 'Kartu pastel lembut ramah Gen-Z, font bulat bersahabat, ikon edukasi rapi.',
    tier: 'PRO',
    available: true,
    accentColor: '#EC4899',
    bgColor: '#FDF2F8',
    textColor: '#1E293B',
    badge: '🔒 PRO',
    instagramRef: '@tentangkampus_id',
  },
  {
    id: 'BOLD',
    label: 'Sport & Dynamic Energy',
    subLabel: 'ala @kepoball',
    description: 'Tipografi miring ultra-bold, efek glow berenergi tinggi, aksen kuning kontras.',
    tier: 'PRO',
    available: true,
    accentColor: '#FACC15',
    bgColor: '#0A0A0A',
    textColor: '#FFFFFF',
    badge: '🔒 PRO',
    instagramRef: '@kepoball',
  },
  {
    id: 'CORPORATE',
    label: 'Karier & Networking',
    subLabel: 'ala @ilmu_networking & @official.indeed',
    description: 'Desain korporat bersih, kartu tips bertingkat, layout profesional LinkedIn.',
    tier: 'PRO',
    available: true,
    accentColor: '#2563EB',
    bgColor: '#0F172A',
    textColor: '#FFFFFF',
    badge: '🔒 PRO',
    instagramRef: '@ilmu_networking',
  },
  {
    id: 'CUSTOM_BRAND',
    label: 'Fakta Pop & Trivia',
    subLabel: 'ala @voxpopular.id & @faktadanmitos',
    description: 'Warna pop vibrant, kartu Fakta vs Mitos, badge Taukah Kamu, memancing rasa penasaran.',
    tier: 'PRO',
    available: true,
    accentColor: '#8B5CF6',
    bgColor: '#1E1B4B',
    textColor: '#FFFFFF',
    badge: '🔒 PRO',
    instagramRef: '@voxpopular.id',
  },
  {
    id: 'MINIMAL',
    label: 'Minimalist Pure',
    subLabel: 'ala Media Seni & Kreatif',
    description: 'Banyak ruang bernapas, minimalis tanpa distraksi, sangat bersih dan estetis.',
    tier: 'PRO',
    available: true,
    accentColor: '#6366F1',
    bgColor: '#090D16',
    textColor: '#FFFFFF',
    badge: '🔒 PRO',
    instagramRef: '@minimalmedia',
  },

  // ─── 10 TEMPLATE MASTER BARU ───
  {
    id: 'STREETWEAR',
    label: 'Streetwear Urban Hook',
    subLabel: 'ala Youth Media & Street Fashion',
    description: 'Foto potret streetwear ukuran penuh dengan kartu putih melayang di sepertiga bawah.',
    tier: 'PRO',
    available: true,
    accentColor: '#FFFFFF',
    bgColor: '#121214',
    textColor: '#000000',
    badge: '✨ BARU',
    instagramRef: '@hypebeastid',
  },
  {
    id: 'BLOOMBERG',
    label: 'Bloomberg Market Terminal',
    subLabel: 'ala Financial Executive',
    description: 'Ticker bar harga pasar berjalan, kontras hijau zamrud, kartu analisis finansial tajam.',
    tier: 'PRO',
    available: true,
    accentColor: '#22C55E',
    bgColor: '#022C22',
    textColor: '#FFFFFF',
    badge: '✨ BARU',
    instagramRef: '@bloombergasia',
  },
  {
    id: 'TERMINAL',
    label: 'MacOS Code Terminal',
    subLabel: 'ala Software & AI Dispatch',
    description: 'Jendela editor kode dengan 3 dot macOS (🔴🟡🟢), font monospace Fira Code & prompt cyan.',
    tier: 'PRO',
    available: true,
    accentColor: '#06B6D4',
    bgColor: '#050811',
    textColor: '#38BDF8',
    badge: '✨ BARU',
    instagramRef: '@codepolitan',
  },
  {
    id: 'ATHLETIC',
    label: 'Nike Athletic Speed Poster',
    subLabel: 'ala RedBull & Nike Sport',
    description: 'Garis balap diagonal 15 derajat, tipografi condensed ekstra tebal, kontras kuning balap.',
    tier: 'PRO',
    available: true,
    accentColor: '#EAB308',
    bgColor: '#000000',
    textColor: '#FFFFFF',
    badge: '✨ BARU',
    instagramRef: '@nikerunning',
  },
  {
    id: 'COSMIC',
    label: 'Observatory Cosmic Science',
    subLabel: 'ala Riset Sains & Astronomi',
    description: 'Pendaran nebula luar angkasa, kisi koordinat teleskop, kartu observasi emas solar.',
    tier: 'PRO',
    available: true,
    accentColor: '#F59E0B',
    bgColor: '#030712',
    textColor: '#FFFFFF',
    badge: '✨ BARU',
    instagramRef: '@nasaindonesia',
  },
  {
    id: 'POLICY',
    label: 'Official Policy White Paper',
    subLabel: 'ala Diplomasi & Regulasi',
    description: 'Double-rule crimson masthead, tipografi serif Playfair berwibawa, format dokumen resmi.',
    tier: 'PRO',
    available: true,
    accentColor: '#DC2626',
    bgColor: '#1C1917',
    textColor: '#FFFFFF',
    badge: '✨ BARU',
    instagramRef: '@kebijakanpublik',
  },
  {
    id: 'SPOTLIGHT',
    label: 'Billboard & Netflix Spotlight',
    subLabel: 'ala Film & Pop Culture',
    description: 'Lencana neon TRENDING #1, kartu kaca frosted ungu-magenta, rating bintang ulasan.',
    tier: 'PRO',
    available: true,
    accentColor: '#D946EF',
    bgColor: '#1E1035',
    textColor: '#FFFFFF',
    badge: '✨ BARU',
    instagramRef: '@netflixid',
  },
  {
    id: 'RED_COLLAGE',
    label: 'Red Highlight Urban Banner',
    subLabel: 'ala Streetwear & Underground Beats',
    description: 'Kolase urban street, inset foto lingkaran, pita merah solid bertumpuk di judul.',
    tier: 'PRO',
    available: true,
    accentColor: '#EF4444',
    bgColor: '#0A0A0C',
    textColor: '#FFFFFF',
    badge: '✨ BARU',
    instagramRef: '@ussfeed',
  },
  {
    id: 'PODCAST',
    label: 'Podcast Interview Persona',
    subLabel: 'ala Sosok Bisnis & Founder Talk',
    description: 'Foto wawancara studio, balon kutipan hitam bertumpuk, lencana sosok inspiratif.',
    tier: 'PRO',
    available: true,
    accentColor: '#000000',
    bgColor: '#F4F4F5',
    textColor: '#18181B',
    badge: '✨ BARU',
    instagramRef: '@podcastfoundertalk',
  },
  {
    id: 'CULINARY',
    label: 'Viral Culinary Neon Indigo',
    subLabel: 'ala Food Vlogger & Kuliner Viral',
    description: 'Foto makanan viral menggiurkan, gradasi midnight indigo pekat bawah, lencana tag lokasi.',
    tier: 'PRO',
    available: true,
    accentColor: '#4F46E5',
    bgColor: '#0F172A',
    textColor: '#FFFFFF',
    badge: '✨ BARU',
    instagramRef: '@kulinerindonesia',
  },
];

export const AVAILABLE_STYLES = STYLES.filter((s) => s.available);
export const FREE_STYLES = AVAILABLE_STYLES.filter((s) => s.tier === 'FREE');
export const PRO_STYLES = AVAILABLE_STYLES.filter((s) => s.tier === 'PRO');
export const DEFAULT_STYLE: DesignStyle = 'BREAKING_NEWS';

export function isProStyle(style: DesignStyle): boolean {
  const def = STYLES.find((s) => s.id === style);
  return def?.tier === 'PRO';
}
